version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run dependency tests
          command: |
            pipenv run python tests/deps.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1